web: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 cbstg.wsgi:application
migrate_collectstatic: python manage.py migrate && python manage.py collectstatic --noinput --clear
create_superuser: python manage.py createsuperuser --username admin --email admin@admin.com --noinput